/*
  ==============================================================================

    Utils.h
    Created: 14 Apr 2023 7:42:44pm
    Author:  zack

  ==============================================================================
*/

#pragma once
#include <JuceHeader.h>


/*
WARNING WARNING WARNING
Templates are a kind of code generation technique, and the actual code is generated by the compiler at compile-time based on the specific type(s) used to instantiate the template. Therefore, the entire implementation of a template function should be visible to the compiler at the point of instantiation.
 WARNING WARNING WARNING
 */

enum FFTOrder
{
    order2048 = 11,
    order4096 = 12,
    order8192 = 13
};

template<
typename Attachment,
typename APVTS,
typename Params,
typename ParamName,
typename SliderType
>
void makeAttachment(std::unique_ptr<Attachment>& attachment,
                    APVTS& apvts,
                    const Params& params,
                    const ParamName& name,
                    SliderType& slider)
{
    attachment = std::make_unique<Attachment>(apvts, params.at(name), slider);
}

template<
typename APVTS,
typename Params,
typename Name
>
juce::RangedAudioParameter& getParam(APVTS& apvts, const Params& params, const Name& name)
{
    auto param = apvts.getParameter(params.at(name));
    jassert(param != nullptr);
    
    return *param;
}

template<typename T>
bool truncateKiloValue(T& value)
{
   if(value > static_cast<T>(999))
   {
       value /= static_cast<T>(1000);
       return true;
   }
   else
   {
       return false;
   }
}

juce::String getValString(const juce::RangedAudioParameter& param, bool getLow, juce::String suffix);

template<
typename Labels,
typename ParamType,
typename SuffixType
>
void addLabelPairs(Labels& labels, const ParamType& param, const SuffixType& suffix)
{
    labels.clear();
    labels.add({0.f, getValString(param, true, suffix)});
    labels.add({1.f, getValString(param, false, suffix)});
}

void drawModuleBackground(juce::Graphics &g, juce::Rectangle<int> bounds);

